p9/urls.py
from django.contrib import admin
from django.urls import path,include
import rsk
from rsk import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('rsk/',include("rsk.urls")),
    path('base/',views.base,name="base"),
    path('home/',views.home,name="home"),
]

rsk/urls.py
from django.urls import path
from rsk import views
app_name="rsk"

urlpatterns = [
    path('trail/',views.trail,name="trail"),
    path('profile/',views.profile,name="profile"),

]

rsk/models.py
from django.db import models

# Create your models here.

rsk/views.py
from django.shortcuts import render
from django.http import HttpResponse


def trail(request):
    return HttpResponse("<h1>Project is on air</h1>")

def base(request):
    return render(request,"base.html")

def home(request):
    return render(request,"rsk/home.html")

def profile(request):
    name="karthi"
    return render(request,"rsk/profile.html",{'name':name})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>base page</title>
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>
<body>
    <div class="alert alert-info" role="alert">
        <center>Top Bar</center>
    </div>
    <div class="container">
        <ul class="nav">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rsk:profile' %}">Profile</a>
            </li>
            
        </ul>
    </div>
    {% block content %}
      <div class="container">
          <div class="jumbotron">
              <h1>Welcome to base page</h1>
          </div>
      </div>
    {% endblock %}
    <div class="alert alert-primary" role="alert">
        <center>Footer</center>
    </div>
</body>
</html>

templates/rsk/home.html
{% extends "base.html" %}

{% block title %}
    <title>Home page</title>
{% endblock %}

{% block content %}
      <div class="container">
          <div class="jumbotron">
              <h1>Welcome to Home page</h1>
          </div>
      </div>
{% endblock %}

templates/rsk/profile.html
{% extends "base.html" %}

{% block title %}
    <title>Profile page</title>
{% endblock %}

{% block content %}
      <div class="container">
          <div class="jumbotron">
              <h1>Welcome to {{name}} profile page</h1>
          </div>
      </div>
{% endblock %}